//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager_device
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETAIL_CHECK
    {
        public string ID_DETAIL { get; set; }
        public string ID_DEVICE { get; set; }
        public Nullable<System.DateTime> DATECHECK { get; set; }
        public string INFOCHECK { get; set; }
    
        public virtual DEVICE DEVICE { get; set; }
    }
}
