//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager_device
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEVICE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEVICE()
        {
            this.HISTORies = new HashSet<HISTORY>();
        }
    
        public string ID_DEVICE { get; set; }
        public string NAME { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public Nullable<System.DateTime> DATEPLAN { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<bool> ENABLE { get; set; }
        public string ID_GROUP { get; set; }
        public string ID_USER { get; set; }
    
        public virtual GROUP_DEVICE GROUP_DEVICE { get; set; }
        public virtual USER USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORY> HISTORies { get; set; }
    }
}
